//actions
export const TEXT_ADDED = "TEXT_ADDED";
export const OBJECT_SELECTED = "OBJECT_SELECTED";
export const TEXTBOX_EVENT = "TEXTBOX_EVENT";
export const SELECTION_CLEARED = "SELECTION_CLEARED";
export const APPEND_TEXT_OBJ = "APPEND_TEXT_OBJ";
